user/urls.py
from django.urls import path

from .import views
app_name='user'
urlpatterns=[
    path('',views.UserBlogview.as_view(),name='index'),
    path('bloglist/<id>',views.BlogListview.as_view(),name='article'),
    path('upload/',views.UserFileview,name='upload'),
    path('download/<id>',views.download,name="download"),
    path('register/',views.Register,name='register'),
    path('login/',views.Login,name='login'),
    path('downloadlist/',views.dowmload_list.as_view(),name='download1')

]

xuexi/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('',include('user.urls')),
    path('admin/', admin.site.urls),

]

user/models.py
from django.db import models


class User(models.Model):
    user_name=models.CharField(max_length=50)
    user_password=models.CharField(max_length=100)
    def __str__(self):
        return  self.user_name
# Create your models here.
class UserBlog(models.Model):
    blog_title=models.CharField(max_length=200)
    blog_content=models.TextField()
    blog_pud_time=models.DateTimeField()

    def __str__(self):
        return  self.blog_title

class UserFile(models.Model):

    file_name=models.CharField(max_length=100)
    file_upload=models.FileField(upload_to='')

    def __str__(self):
        return  self.file_name

user/views.py
from django.shortcuts import render,render_to_response
from  django.http import HttpResponseRedirect,HttpResponse,StreamingHttpResponse
from django.views import generic
from .models import User,UserBlog,UserFile
from .form import UserRegister,UserLogin,UserFileForm
import hashlib,os
from django.template import RequestContext


def take_sha1(content):

    ct=content.encode(encoding='UTF-8',errors='strict')
    hs=hashlib.sha224()

    result=hs.update(ct)
    return result


class UserBlogview(generic.ListView):
    template_name = 'user/index.html'
    def get_queryset(self):
        return  UserBlog.objects.order_by('blog_pud_time')[:8]




class BlogListview(generic.DetailView):
    model = UserBlog
    template_name = 'user/article.html'

class UserView(generic.ListView):

    template_name = 'user/index.html'

    def get_queryset(self):
        return User.objects.order_by('id')[:3]

def handle_upload_file(f):


    with open(os.path.join("D:\DTLFolder",f.name),"wb+") as destination:

       for chunk in f.chunks():
           destination.write(chunk)
           destination.closed


def UserFileview(request):
  if request.method=='POST':
    form=UserFileForm(request.POST,request.FILES)

    print( form.is_valid())
    if form.is_valid():






        file_name=form.cleaned_data['file_name']
        file_upload=form.cleaned_data['file_upload']
        handle_upload_file(request.FILES['file_upload'])
        #file_upload=os.path.join("D:\DTLFolder",request.FILES['file_upload'].name)
        print('111111ceshi')
        user_file=UserFile.objects.create(file_name=file_name,file_upload=file_upload)
        print('222222222211111ceshi')
        #print(request.FILES['file_upload'].name)
        user_file.save()
        print(request.FILES['file_upload'].name)

        return HttpResponse("文件上传成功")


  else:
      form=UserFileForm()
      return render(request,'user/upload.html',{form:form})
class dowmload_list(generic.ListView):
    template_name = "user/upload.html"
    def get_queryset(self):
        return UserFile.objects.order_by('id')

def download(request,id):
    f1=UserFile.objects.get(pk=id)
    def file_iterator(file_name,chunk_size=512):
       with open(file_name,'rb+') as readfile:
           while True:
            c=readfile.read(chunk_size)
            if c:
                  yield c
            else:
                  break
    file_name=f1.file_upload
    #f="D:/DTLFolder/pycharm.txt"
    f=os.path.join('C:/Users/Administrator/PycharmProjects/xuexi',file_name.path)
    print(f)
    print(file_name)
    print(os.path.dirname(__file__))
    #path='/'.join(file_name)


    response=StreamingHttpResponse(file_iterator(f))
    response['Content-Type'] = 'application/octet-stream'
    response['Content-Disposition'] = 'attachment;filename="{0}"'.format(f)
    return response




def Register(request):
    if request.method=='POST':
        form=UserRegister(request.POST)
        if form.is_valid():
            user_name=form.cleaned_data["user_name"]
            namefilter=User.objects.filter(user_name=user_name)
            if len(namefilter)>0:
                return  render(request,'user/register.html',{'error':'用户名已经存在'}
                                           )
            else:
                user_password=form.cleaned_data['user_password']
                user_password_sure=form.cleaned_data['user_password_sure']
                if user_password !=user_password_sure:
                    return render(request,'user/register.html',{'error':'两次输入密码不一致！重新输入'}
                                              )
                else:
                  user_password=user_password_sure
                  print(take_sha1(user_password_sure))
                  print(take_sha1("mmmm"))


                  user=User.objects.create(user_name=user_name,user_password=user_password)
                  user.save()
                  return render(request,'user/success.html',{'user_name':user_name,'message':'注册成功'}
                                              )

    else:
        form = UserRegister()
        return render(request,'user/register.html', {'form': form}
                                )



def Login(request):
    if request.method=='POST':
        form=UserLogin(request.POST)
        if form.is_valid():
            user_name=form.cleaned_data['user_name']
            user_password=form.cleaned_data['user_password']
            user_password=user_password
            namefiter=User.objects.filter(user_name=user_name,user_password=user_password)
            if len(namefiter)>0:
                return render(request,'user/success.html',{'user_name':user_name,'message':'登录成功'}
                                          )
            else:
                return render(request,'user/login.html',{'error':'用户不存在，或者用户名密码不对'}
                                          )
    else:
            form=UserLogin()
            return render(request,'user/login.html',{'form':form})


# Create your views here.

user/templates/user/article.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <script rel="script"  src="https://apps.bdimg.com/libs/jquery/2.1.4/jquery.min.js"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'user/style.css'%}">
    <meta charset="UTF-8">
    <title>{{userblog.blog_title }}</title>
</head>
<body>
<div>
    <h2>{{userblog.blog_title }}</h2>
    <table>
        <tr>
           发布时间： {{ userblog.blog_pud_time }}
        </tr>
    </table>
    <p class="text">{{userblog.blog_content }}</p>
   <button>点我隐藏内容</button>
</div>
</body>
<script>
   $(document).ready(function () {
       $("button").click(function () {
           $(".text").hide()
       })

   })
</script>
</html>

user/templates/user/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>我的博客</title>

</head>
<body>
<h1>欢迎访问我的博客</h1>
{% if  userblog_list  %}


     <div>
     {% for userblog in userblog_list %}

         <a href="../bloglist/{{ userblog.id }}">{{userblog.blog_title }}</a><br/>




      {% endfor %}
 {% else %}
    {{ "文章不存在" }}

{% endif %}
</div>

</body>
</html>

user/templates/user/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'user/style.css'%}">
    <meta charset="UTF-8">
    <title>登录</title>
</head>
<body>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    {{ error }}
    <input type="submit" value="登录">
    <a href="{% url 'user:register' %}">注册</a>
</form>
</body>
</html>

user/templates/user/register.html
<!DOCTYPE html>
<html lang="zh-hans">
<head>
    <meta charset="UTF-8">
    <title>注册</title>
</head>
<body>
<form action="."   method="post">
    {% csrf_token %}
    {{ form.as_p }}
    {{ error }}
    <input type="submit"  value="注册">
</form>
{{ user }}
</body>
</html>

user/templates/user/success.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>注册成功</title>
</head>
<body>
<h1>恭喜注册成功！</h1>
<a href="http://127.0.0.1:8000/login/">返回登录界面</a>
</body>
</html>

user/templates/user/upload.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <link href="//vjs.zencdn.net/6.7/video-js.min.css" rel="stylesheet">
    <script src="//vjs.zencdn.net/6.7/video.min.js"></script>

    <link rel="stylesheet" type="text/css" href="{% static 'user/style.css' %}">
    <meta charset="UTF-8">
    <title>文件上传</title>
</head>
<body>
<form action=""  method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="text" name="file_name">
    <input type="file" name="file_upload">



    <input type="submit"  value="上传">
</form>
{% if  userfile_list  %}


     <div>
     {% for userfile in userfile_list %}

         <a href="../download/{{ userfile.id }}">{{userfile.file_name }}</a><br/>





      {% endfor %}
      <img src="../download/11">
     <video  controls="controls">
         <source src="../download/13" type="video/ogg">
         <source src="../download/13" type="video/mp4">
         Your browser does not support the video tag.
     </video>
 {% else %}
    {{ "文件不存在" }}
    </div>

{% endif %}
<video
    id="my-player"
    class="video-js"
    controls
    preload="auto"
    poster="//vjs.zencdn.net/v/oceans.png"
    data-setup='{}'>
  <source src="../download/16" type="video/mp4"></source>
  <source src="../download/16" type="video/webm"></source>
  <source src="../download/16" type="video/ogg"></source>
  <p class="vjs-no-js">
    To view this video please enable JavaScript, and consider upgrading to a
    web browser that
    <a href="http://videojs.com/html5-video-support/" target="_blank">
      supports HTML5 video
    </a>
  </p>
</video>

</body>

</html>